# Colores
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"
set -as terminal-features ",xterm-256color:RGB"
set -g terminal-overrides ",*:cursorshape=3"

# Base index
set -g base-index 1
set -g pane-base-index 1

# status bar
set -g status-position top
set -g status-style "bg=default,fg=white"

set -g status-left " #[bg=default,fg=white]#S | "
set -g status-left-length 32 
set -g status-right "#[bg=default,fg=white] #{?client_prefix,PREFIX,NORMAL} "

set -g window-status-format "#I:#W"
set -g window-status-current-format "#I:#W"

set -g window-status-style "bg=default,fg=grey"
set -g window-status-current-style \
    "#{?window_zoomed_flag,bg=yellow,bg=default,fg=white}"

set -g message-style "bg=default,fg=white"

set -g mode-style "bg=white,fg=black"

set -g renumber-windows on

# Bordes del panel
set -g pane-border-lines single
set -g pane-border-style fg=grey
set -g pane-active-border-style fg=white

# Atajos de teclado
unbind C-b
set -g prefix C-space
bind C-space send-prefix

unbind %
bind - split-window -v

unbind '"'
bind | split-window -h

# moverse entre paneles
bind -n C-j select-pane -t :.+
bind -n C-k select-pane -t :.-
bind f resize-pane -Z

# nueva ventana
bind t new-window

unbind r
bind r source-file ~/.tmux.conf

# Extras
set -s escape-time 0
