#!/bin/sh

opciones="Dracula\nGruvbox\nMinimal\nMurz\nNord\nOnedark\nCancelar"
selec=$(echo $opciones | rofi -dmenu -i -p "Selector de temas")
case $selec in
	Dracula) cp $HOME/.config/i3/themes/dracula.conf $HOME/.config/i3/theme.conf
			 cp $HOME/.config/polybar/themes/dracula.ini $HOME/.config/polybar/config.ini
			 cp $HOME/.config/lxterminal/themes/dracula.conf $HOME/.config/lxterminal/lxterminal.conf ;;
	Gruvboc) cp $HOME/.config/i3/themes/gruvbox.conf $HOME/.config/i3/theme.conf
			 cp $HOME/.config/polybar/themes/gruvbox.ini $HOME/.config/polybar/config.ini
			 cp $HOME/.config/lxterminal/themes/gruvbox.conf $HOME/.config/lxterminal/lxterminal.conf ;;
	Minimal) cp $HOME/.config/i3/themes/minimal.conf $HOME/.config/i3/theme.conf
			 cp $HOME/.config/polybar/themes/minimal.ini $HOME/.config/polybar/config.ini
			 cp $HOME/.config/lxterminal/themes/minimal.conf $HOME/.config/lxterminal/lxterminal.conf ;;
	Murz)	 cp $HOME/.config/i3/themes/murz.conf $HOME/.config/i3/theme.conf
			 cp $HOME/.config/polybar/themes/murz.ini $HOME/.config/polybar/config.ini
			 cp $HOME/.config/lxterminal/themes/murz.conf $HOME/.config/lxterminal/lxterminal.conf ;;
	Nord)    cp $HOME/.config/i3/themes/nord.conf $HOME/.config/i3/theme.conf
			 cp $HOME/.config/polybar/themes/nord.ini $HOME/.config/polybar/config.ini
			 cp $HOME/.config/lxterminal/themes/nord.conf $HOME/.config/lxterminal/lxterminal.conf ;;
	Onedark) cp $HOME/.config/i3/themes/onedark.conf $HOME/.config/i3/theme.conf
			 cp $HOME/.config/polybar/themes/onedark.ini $HOME/.config/polybar/config.ini
			 cp $HOME/.config/lxterminal/themes/onedrak.conf $HOME/.config/lxterminal/lxterminal.conf ;;
	Cancelar)
		exit 0 ;;
esac
