#!/bin/sh

# Escanea las redes Wi-Fi disponibles y extrae los SSIDs y la seguridad
networks=$(connmanctl scan wifi)

# Muestra el menú con rofi y guarda la selección
selected_network=$(echo "$networks" | rofi -dmenu -p "Wi-Fi")
#| awk -F: '{print $1}'

# Si el usuario selecciona una red
if [ -n "$selected_network" ]; then
    
    # Si la red tiene seguridad (no es una red abierta)
    if [ "$security" != "--" ]; then
        # Pregunta la contraseña
        wifi_password=$(rofi -dmenu -p "Contraseña para $selected_network")

        # Conectar a la red seleccionada con contraseña
        if [ -n "$wifi_password" ]; then
			connmanctl connect "$selected_network" password "$wifi_password"
        else
            echo "Contraseña vacía, no se pudo conectar."
        fi
    else
        # Conectar a la red abierta
        connmanctl connect "$selected_network"
    fi
fi
