#! /bin/sh

# Inicio automatico
~/.config/bspwm/autostart.sh

# Nombre de los colores
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Programas con escritorio definido
bspc rule -a Firefox desktop= '^3'
bspc rule -a Discord desktop= '^10'
bspc rule -a TelegramDesktop desktop= '^10'

# Personalizacion
bspc config border_width        2
bspc config window_gap          2
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
~/.config/bspwm/theme.sh
