#!/bin/sh

AppImage="$HOME/appimage"
selec=$(find $AppImage -type f -iname "*.AppImage" -printf "%f\n"|
        sed 's/\.AppImage$//' | sort | dmenu -i)
[ -n "$selec" ] && "$AppImage/$selec.AppImage"
